apiVersion: v1
kind: Service
metadata:
  name: multi-container-service
  namespace: malarvizhi
  annotations:
    description: "Exposes the multi-container deployment externally" 
  labels: 
    app: multi-container-app
    service-type: external
spec:
  type: NodePort
  selector:
    app: multi-container-app
  ports:
    - port: 80
      
      targetPort: 80
  
      nodePort: 32000
