version: '3.8'

services:
  front-end:
    image: tecvinson-app-fe:v1
    container_name: tecvinson-app-fe
    ports:
     - "419:80"
    #depends-on:back-end
    networks:
     - devops-network
  
  back-end:
    image: tecvinson-app-be:v1
    container_name: tecvinson-app-be
    ports:
     - "5500:5500"
    environment:
      - ENV FLASK_APP=app.py
      - ENV MYSQL_HOST=tecvinson-app-db
      - ENV MYSQL_ROOT_PASSWORD=rootpassword
      - ENV MYSQL_DATABASE=tecvinson_registration
    networks:
      - devops-network
  
  database:
    image: tecvinson-app-db:v1
    container_name: tecvinson-app-db
    ports:
     - "3306:3306"
    networks:
      - devops-network
    volumes:
      - "sql_data:/var/lib/mysql"
    environment:
      - ENV MYSQL_ROOT_PASSWORD=rootpassword=value
      - ENV MYSQL_DATABASE=tecvinson_registration
    
  

networks:
  devops-network: {}

volumes:
  sql_data:
  


      