apiVersion: v1
kind: Namespace
metadata:
    name: hassan-ns


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-container-deployment
  namespace: hassan-ns
  labels:
    app: multi-container-app
    env: production

spec:
  replicas: 3
  selector:
    matchLabels:
      app: multi-container-app
  template:
    metadata:
      labels:
        app: multi-container-app
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 90
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
