apiVersion: v1
kind: Service
metadata:
  name: multi-container-service
  namespace: igho                           # Same namespace as the Deployment
  labels:
    app: multi-container-app
    service-type: external
  annotations:
    description: "Exposes the multi-container deployment externally"
spec:
  type: NodePort
  selector:
    app: multi-container-app                # Matches the Deployment's label
  ports:
    - port: 80                              # Service port
      targetPort: 80                        # Target port on app-container
      nodePort: 32000                       # Choose a NodePort in the range 30000-32767
