name: Lint Code Base

# This workflow will run on pull requests and pushes to main
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      # Checkout the code in the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Run Super-Linter
      - name: Run Super-Linter
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: true  
          DEFAULT_BRANCH: main         
          GITHUB_TOKEN: ${{ secrets.vm }}
