name: Update Submission Board

on:
  schedule:
    - cron:  '0 0 * * *'  # Runs at midnight every day
  workflow_dispatch:
permissions:
  contents: write
env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  GITHUB_REPOSITORY: ${{ github.repository }}
  GITHUB_REF: ${{ github.ref }}

jobs:
  check-submissions:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install dependencies
      run: pip install PyGithub

    - name: Check Submissions
      run: |
        python scripts/check_submissions.py
        
    - name: Commit and Push Changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Automated README update" || echo "No changes to commit"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GH_TOKEN }}
        branch: update-readme-branch-${{ github.run_id }}
        commit-message: "Automated README update"
        title: "Automated README Update"
        body: "This PR was automatically generated by tecvinsonbot to update the README.md file."
        base: main
        delete-branch: true

  automerge:
    needs: check-submissions
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
