name: Test and Merge Bash Script

on:
  pull_request:
    branches:
      - main
    paths:
      - 'bash-scripting/**'
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
    paths:
      - 'bash-scripting/**'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  test_and_merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR code safely
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Get list of changed files
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            scripts:
              - '**.sh'

      - name: Debug scripts output
        shell: bash
        run: |
          echo "Scripts to lint: ${{ steps.filter.outputs.scripts }}"

      - name: Install ShellCheck
        shell: bash
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Lint the scripts with ShellCheck
        if: ${{ steps.filter.outputs.scripts == 'true' }}
        run: |
          for file in ${{ steps.filter.outputs.scripts }}; do
            echo "Running ShellCheck on $file"
            shellcheck "$file"
          done

      - name: Set up Docker container
        run: docker pull ubuntu:20.04

      - name: Execute the scripts in Docker
        if: ${{ steps.filter.outputs.scripts == 'true' }}
        run: |
          echo "${{ steps.filter.outputs.scripts  }}" | tr ' ' '\n' | while read file; do
            echo "Executing $file in Docker"
            docker run --rm \
              -v "${{ github.workspace }}":/workspace \
              -w /workspace \
              ubuntu:20.04 \
              bash -c "
                apt-get update && \
                DEBIAN_FRONTEND=noninteractive apt-get install -y sudo && \
                chmod +x $file && \
                sudo $file
              "
          done

      - name: Approve Pull Request
        if: ${{ steps.filter.outputs.scripts == 'true' && success() }}
        uses: juliangruber/approve-pull-request-action@v2.0.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.pull_request.number }}
