name: ShellCheck Linting

# Define the triggers for the workflow
on:
  workflow_dispatch:

# Define the jobs to be run
jobs:
  lint:
    name: Lint Bash Scripts with ShellCheck
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Run ShellCheck on scripts in bash-scripting directory
      - name: Run ShellCheck
        continue-on-error: true
        uses: azohra/shell-linter@latest
        with:
          path: "bash-scripting"

      - name: Upload ShellCheck Report
        uses: actions/upload-artifact@v3
        with:
          name: shellcheck-report
          path: shellcheck_report.txt
